site_name: Zhenda Nas Docs

nav:
  - 首页: index.md
  - 什么是 NAS?: overview/what-is-nas.md
  - 快速开始: quickstart/first-config.md
  # - 概述:
  #   - overview/index.md
  #   - 什么是 NAS?: overview/what-is-nas.md
  #   - 硬件选择: overview/hardware.md
  #   - 家庭媒体中心: overview/home-media-center.md
  #   - 小企业NAS: overview/small-business-nas.md
  #   - 系统安装: overview/installation.md
  # - 快速开始: 
  #   - quickstart/index.md
  #   - 首次配置: quickstart/first-config.md
  #   - Docker 部署: quickstart/docker-tutorial.md
  #   - 网络优化: quickstart/network-optimization.md
  #   - 系统监控: quickstart/monitoring.md
  - 应用指南:
    # - applications/index.md
    - 系统工具:
      - Portainer 控制面板: applications/system/portainer.md
      - Glances 系统监控: applications/system/glances.md
      - FileBrowser 文件浏览: applications/system/filebrowser.md
      - Duplicati 备份工具: applications/system/duplicati.md
      - Frp 内网穿透: applications/system/frp.md
    - 下载工具:
      - metube 下载中心: applications/download/metube.md
      - Aria2 下载中心: applications/download/aria2.md
      - qBittorrent: applications/download/qbittorrent.md
    - 媒体工具:
      - Jellyfin: applications/media/jellyfin.md
      - Metatube: applications/media/metatube.md
      # - Stash: applications/media/stash.md
      - Immich: applications/media/immich.md
      - Navidrome: applications/media/navidrome.md
      - Music-tag-web: applications/media/music-tag-web.md
    # - 生产力工具:
    #   - GitLab: applications/productivity/gitlab.md
    #   - Gitea: applications/productivity/gitea.md
    #   - Wiki: applications/productivity/wiki.md
    #   - 密码管理: applications/productivity/password-manager.md
    - 其他工具:
      - Homer: applications/other/homer.md
      - Homepage: applications/other/homepage.md
      - Dashy: applications/other/dashy.md
      - Nextcloud: applications/productivity/nextcloud.md
      - cloudreve 私有云: applications/other/cloudreve.md
      - CasaOS: applications/other/casaos.md
  - 进阶配置: 
    - 远程访问: advanced/remote.md
    - 备份策略: advanced/backup-strategies.md
    - 高可用策略: advanced/high-availability.md
    # - 备份策略test: advanced/backup-test.md
    - 安全设置: advanced/security.md
    - 自动化脚本: advanced/automation-scripts.md
  #   - VPN设置: advanced/vpn-setup.md
  #   - SSL证书: advanced/ssl-certificates.md
  - 常见问题: troubleshooting.md
# theme: readthedocs
theme:
  name: material
  # language: zh
  # language: en
  features:
    - navigation.instant           # 即时导航
    - navigation.instant.prefetch  # 即时导航预加载
    # - navigation.tabs  # 顶部使用 Tab
    # - navigation.tabs.sticky  # 悬浮固定
    - navigation.expand  # 侧边栏默认展开
    # - navigation.indexes  # 侧边栏索引
    - navigation.path  # 面包屑导航
    - navigation.top  # 返回顶部
    - navigation.tracking  # 锚点跟踪
    - navigation.footer    # 底部导航
    # - navigation.sections      # 侧边栏展开不会折叠
    - search.suggest
    - search.highlight
    # - search.share            # 搜索分享
    - content.code.copy  # 代码块添加复制按钮
    # - content.code.annotate
    - content.action.edit
    - content.action.view
    - toc.follow  # 侧边栏会自动滚动
    # - toc.integrate           # 目录集成
  palette:
    # - scheme: default  # 浅色模式
    #   primary: indigo  # 主色调：靛蓝
    #   accent: blue     # 强调色：深蓝
    #   toggle:
    #     icon: material/weather-night
    # - scheme: slate    # 暗色模式
    #   primary: indigo
    #   accent: blue
    #   toggle:
    #     icon: material/weather-sunny
    # - scheme: default
    #   primary: teal
    #   accent: light-green
    #   toggle:
    #     icon: material/weather-night
    # - scheme: slate
    #   primary: teal
    #   accent: light-green
    #   toggle:
    #     icon: material/weather-sunny
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
    # - scheme: default
    #   primary: orange
    #   accent: amber
    #   toggle:
    #     icon: material/weather-night
    # - scheme: slate
    #   primary: orange
    #   accent: amber
    #   toggle:
    #     icon: material/weather-sunny
    # - scheme: default
    #   primary: brown
    #   accent: red
    #   toggle:
    #     icon: material/weather-night
    # - scheme: slate
    #   primary: brown
    #   accent: red
    #   toggle:
    #     icon: material/weather-sunny
    # - scheme: default
    #   primary: grey
    #   accent: cyan
    #   toggle:
    #     icon: material/weather-night
    # - scheme: slate
    #   primary: grey
    #   accent: cyan
    #   toggle:
    #     icon: material/weather-sunny

        # icon: material/weather-night
        # icon: material/weather-sunny
        # icon: material/lightbulb-outline
        # icon: material/lightbulb

plugins:
  - search
  # - i18n:
  #     default_language: zh
  #     languages:
  #       - locale: zh
  #         name: 简体中文
  #         default: true
  #         build: true
  #       - locale: en
  #         name: English
  #         build: true

  # - blog

copyright: Copyright &copy; 2025 zhenda


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true               # 行号锚点
      line_spans: __span                  # 行跨度
      pygments_lang_class: true           # 语言类名
      auto_title: true                    # 自动标题
      linenums: true                      # 显示行号
      linenums_style: pymdownx-inline     # 行号样式
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  # ✅ 语法高亮 + 代码增强
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid                   # Mermaid图表支持
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite                  # Vega-Lite图表支持
          class: vegalite
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
