version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "80:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: alice
      PASSWORD: secret1234
    volumes:
      - /srv/dav:/var/lib/dav

# https://hub.docker.com/r/bytemark/webdav/





```bash
docker run -d \
  --name webdav \
  -p 8080:80 \
  -v /本地目录:/var/www/webdav \
  -e USERNAME=用户名 \
  -e PASSWORD=密码 \
  xamaera/nginx-webdav
```