services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
      - ./cookies:/cookies
    environment:
  
      OUTPUT_TEMPLATE: >-
        %(playlist_title&Playlist |)s%(playlist_title|)s%(playlist_uploader& by |)s%(playlist_uploader|)s%(playlist_autonumber& - |)s%(playlist_autonumber|)s%(playlist_count& of |)s%(playlist_count|)s%(playlist_autonumber& - |)s%(uploader,creator|UNKNOWN_AUTHOR)s - %(title|UNKNOWN_TITLE)s - %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)s.%(ext)s
        %(playlist_title&Playlist |)S%(playlist_title|)S%(playlist_uploader& by |)S%(playlist_uploader|)S%(playlist_autonumber& - |)S%(playlist_autonumber|)S%(playlist_count& of |)S%(playlist_count|)S%(playlist_autonumber& - |)S%(uploader,creator|UNKNOWN_AUTHOR)S - %(title|UNKNOWN_TITLE)S - %(release_date>%Y-%m-%d,upload_date>%Y-%m-%d|UNKNOWN_DATE)S.%(ext)s
        
        
      YTDL_OPTIONS: >-
        {
          "cookiefile": "/cookies/cookies.txt",
          "add_metadata": true,
          "writesubtitles": true,
          "writeautomaticsub": false,
          "subtitleslangs": ["zh", "en", "ko", "-live_chat"],
          "subtitlesformat": "srt",
          "embedsubtitles": false,
          "updatetime": false,
          "writethumbnail": false,
          "writeinfojson": false,
          "restrictfilenames": true,
          "postprocessors": [
            {
              "key": "Exec",
              "exec_cmd": "chmod 0664",
              "when": "after_move"
            },
            {
              "key": "FFmpegEmbedSubtitle",
              "already_have_subtitle": false
            },
            {
              "key": "FFmpegMetadata",
              "add_chapters": true
            }
          ]
        }
