version: '3.8' 
services:
  v2raya:
    image: mzz2017/v2raya
    restart: always
    container_name: v2rayamzz
    network_mode: host 
    privileged: true 
    cap_add:  
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "2017:2017"
      - "7890:7890"
    volumes:
      - ./etc:/etc/v2raya